siteTitle = "Kan Ouivirach - Research & Development Engineer at Pronto Tools"
siteDescr = "Being interested in Agile software development, I joined an Agile team at Pronto Tools as a  Machine Learning Enthusiast and Research & Development Engineer. I am an engineer who not only has a scientific mindset, but also a practical approach to software solutions."
siteAuthor = "Kan Ouivirach"

siteTelegramUrl = "#"
siteTwitterUrl = "https://twitter.com/zkancs"
siteGithubUrl = "https://github.com/zkan"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = ""

linkPrefix = "/gatsby-starter-lumen"
